### PR TITLE
Apply the Same Type of Fault Injector to Multiple Registers

### PR DESCRIPTION
**Pull request by aroelke**
Chiffre stores fault injectors in a map of injector type onto injector info, which means that there can only be at most one of each type of injector.  By refactoring that map to use annotated components as keys, it is possible to annotate multiple registers with the same fault injector.

This creates a difficulty with generating the scan chain bitstream, as simply inputting global injector parameters via command line might not make sense.  Injectors have been changed to include their parameters as optional class parameters so that they get serialized along with their class names and widths.  The scan chain bitstream generator tool has been modified to read injector parameters from the scan chain JSON description rather than the command line.

For example, the new scan chain JSON file might look like this:
```
{
  "main":[
    {
      "name":"TestHarness.CSRFile.reg_frm",
      "injector":{
        "class":"chiffre.scan.StuckAtInjectorInfo",
        "width":3,
        "mask":7,
        "value":0
      }
    },
    {
      "name":"TestHarness.CSRFile.reg_fflags",
      "injector":{
        "class":"chiffre.scan.StuckAtInjectorInfo",
        "width":5,
        "mask":31,
        "value":0
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by seldridge** [comment]
I'm highly in favor of the broad idea here. I think there's a fundamental problem with my code that it would make sense to fix here (which I am intending to take care of as part of the testing): The scan chain JSON should contain information about the value of a specific `ScanField`, but as you get at, this can be unbound so it's an `Option[BigInt]`. However, I do think that this should live with the `ScanField` and not with the `InjectorInfo`. The `InjectorInfo` contains fields which have values, but the `InjectorInfo` doesn't deal with the actual values directly. Without custom JSON serializers/deserializers, this means that the `InjectorInfo` case class needs to be given all the information about the `Seq[ScanField]` that it contains. That seems inelegant and I'm considering flattening `InjectorInfo` to a `Seq[ScanField]` and have the `Injector`s implement that.

This, like with your solution here, mean that the JSON includes all the information about the scan chain, including information about binding, and that can be edited directly to set specific fields differently. The ability of setting different fields was something that I had known needed to be done, but had not thought of a solution. I thought about some GUI, but it's a lot easier to deal with editing the JSON (and then writing a simple graphical JSON editor or using some library that already exists) than doing some custom solution.

**Comment by aroelke** [comment]
I think it could make sense for `InjectorInfo` if you think of `InjectorInfo` as the specification for the injector.  In that case, it would want to contain all of the parameters of the injector, including fields widths and values.  Though if this ends up being just a `Seq[ScanField]`, then I guess there's no reason to keep a separate class.  It does allow you to encapsulate behaviors like derivations of default values, though, and gives a convenient place to go when looking for an injector's specification.

In any case, after thinking about it I don't think using `Option[A]` is a good idea for scan field data.  When you serialize `Option`s, the JSON serializer completely omits fields if they are `None`, which makes it unclear to anyone editing the JSON output what the fields are.  If `None` is just going to get resolved into a default value anyway (which it has to), then you might as well just make that value be the default for the parameter (so, rather than `value: Option[BigInt]`, use `value: BigInt = <default>`).  Then the serializer will include it in the JSON file.

**Comment by seldridge** [comment]
I've got to think here. I'm not a big fan of json4s removing optional fields. We can use a custom serializer here if needed. 

I like the abstraction of "binding" free scan chain fields to concrete values, but that means that you have to have some representation of unbound. `Option[BigInt]` works well here, but alternatively, we could use an `Either[String, BigInt]` where the `Left[String]` would provide information about what the user should fill in. The other alternative is `Try`, but that doesn't seem to make sense to me. Using `Either` would require a custom serializer, I think. 

Do you like the bound/unbound abstraction? I think it makes sense to use the best abstraction we can think of and beat json4s into submission as opposed to limiting ourselves to whatever it provides. You, as a user, can provide some info on how you want to use this.

**Comment by aroelke** [comment]
That seems relatively complicated for something I think could be straightforward.  I don't think I'm particularly attached to how it's implemented under the hood, but I do think that the output scan chain JSON file should contain the name of each scan chain, the name of each element that is being injected, the type and width of the injector that is applied to it, and name/value pairs for each of that injector's fields.  My issue with using `Option[A]` is that it suggests (to me, anyway) that the field is optional, but when you store a default value upon receiving `None`, it's not really optional.  It would seem to me that receiving `None` for a field should not only omit it from the output scan chain JSON, but also omit the corresponding hardware/funcationality.  I think the current implementation using case classes and json4s to serialize/deserialize them works fine for this.

**Comment by seldridge** [comment]
I think there are two approaches here:
  - Scan chains are bound/unbound and do not have default values
  - Scan chains are always bound and are given default values

I liked the notion of binding, but that results in the need for something capable of representing the lack of a value (`Option`, `Either`, `Try`, or *gasp* `null`). An unbound scan chain is illegal when the `Driver` tries to generate a bitstream and the user is given information that they need to fully describe what the scan chain needs. 

I think the issue here is that `Option` in Scala is somewhat overloaded to be a safe replacement for `null` and can also be used to represent something that is truly "optional". Json4s seems to only view this from the latter representation. Quickly looking at this, Json4s does have some support for `JNothing` and `JNull`. Serialization using that may make sense.

Note: if we keep the notion of bound/unbound, we can add an "enableable" bit to each `ScanField` that would force this unit off if it's unbound allowing for unbound scan chains to be used.

**Comment by aroelke** [comment]
I think I might be a little unclear on what you mean by bound/unbound, since it seems to me that there has to be some value for each injector field for it to function.  Can you give me an example of when a lack of value might be appropriate?

**Comment by seldridge** [comment]
Sure! I don't really articulate this anywhere...

This abstraction grew from me thinking about the two-stage process of (1) generating a scan chain and (2) setting the values in that scan chain. The `ScanChainTransform` is responsible for generating the _unbound_ description in JSON and `ScanChainConfig` is responsible for reading this description and setting all free values to something. The process of what the `ScanChainConfig` does is _binding_. This then defines the notion of _bound_ and _unbound_ `ScanFields` where a bound `ScanField` has a value (`value.nonEmpty == true`) and an unbound `ScanField` does not have a value (`value.isEmpty == true`). A bound scan chain has all `ScanField`s bound and an unbound scan chain has one or more unbound `ScanField`s.

> [...] since it seems to me that there has to be some value for each injector field for it to function.

Exactly. Rephrased, the `ScanChainTransform`, in my view, doesn't have enough information to set the values for each injector field. Hence, it emits unbound fields. I wanted to have some way to encode "unboundedness" so that `ScanChainConfig` could know that it's done it's job.

The origin of this came from me thinking about user APIs to `ScanChainConfig`. The CLI API that I originally wrote is one example of this, however, I could imagine others, e.g., graphical, menu based, etc. In the CLI API, you'd like to have some way of indicating that the user hasn't specified something that they should have, e.g., the user hasn't specified a probability, but they have an `LfsrInjector` in their design. Default values don't encode enough information to do this, but it's an alternative.

Does this bound/unbound abstraction make sense to you?

**Comment by aroelke** [comment]
Yes, that does make sense, thank you.  In that case, `Option[A]` is probably the best way to go *except* that json4s omits `None` values from the JSON output.  So this boils down to two problems:  How to get the serializer to output fields with `None` values, and what to represent them as. 

Unless I'm mistaken, JSON only has three data types: map, array, and string.  So, the latter question is easily answered by using the empty forms of those types (i.e. `{}`, `[]`, and `""`, respectively, unless JSON doesn't allow that). I suspect that json4s will accommodate us if we just default bind map and array parameters to their empty values, but we can't do that with scalars unless we make them be strings and do string conversion in the injector, which is clunky.  Do you know if you can make json4s output an empty string for `None`?

**Comment by seldridge** [comment]
My cursory inspection of Json4s indicates that it supports two "null" types: `JNoting` and `JNull`. Both of these supposedly deserialize to `None`. So, a custom serializer, like what is used for `firrtl.annotations.Named` may work. Or: that would be the first thing to try.

**Comment by seldridge** [comment]
Another thing that just occurred to me. _We don't have to emit the `None` field in the JSON_. I view manually editing the JSON as an advanced API. Or, the user has to know that every `ScanField` needs to be given a value. If we're working with a higher-level API (CLI, GUI, etc.) then that will not operate on the JSON directly, but deserialize it and have all of the binding and checking methods available. 

I had viewed it as a requirement that the JSON made the value visible, but it's not really required. If the user uses an advanced API, then they should know what they're doing. Additionally, if no default value is found in `ScanChainConfig`, we're in a position to provide a very good error message indicating exactly which field of which component's injector is unbound and suggesting that the user go fix it.

I worked on a small test case trying to change the behavior of how json4s serializes `Option` (something that it already knows how to serialize). I have not verified this, but I expect it's doing pattern matching and I'm having trouble getting this to override the default "None" serialization. 

I agree with your point about stringly typed fields being klunky. We could do that as values are strictly `Option[BigInt]` and can never be `Option[String]` or something else that would conflict.

**Comment by aroelke** [comment]
No, I think we do need to include `None` fields in the JSON because that allows us to decouple whatever binding mechanism that gets developed from the Chiffre source code.  That may not seem important, but it will make it a lot easier to create new fault injectors, especially if the binding mechanism is a GUI (which it probably should include).  If `None` fields are represented in the JSON, then the binding mechanism can just read them and warn/error if they are empty rather than having to know what they are internally and see that they are not included.  This also facilitates lower-level binding between now and when the "official" binding mechanism is created.

Would it be especially painful to create our own serializer?  I don't think JSON is all that complicated.

**Comment by seldridge** [comment]
> No, I think we do need to include None fields in the JSON because that allows us to decouple whatever binding mechanism that gets developed from the Chiffre source code.

Can you clarify on why you think the binding mechanism should be decoupled? 

It's possible to do, but it's a lot easier to not. I've always thought that a GUI, like with the CLI `ScanChainConfig`, would deserialize the JSON back to a `ScanChain`. If you do this, then you are dealing with a `Seq[ScanField]` and all `Option`s are set to something. I think you're talking about going to a `Seq[JsonObject]` and manipulating that? Seems like there's semantic information lost there.

If you are writing a GUI JSON editor, then including `None` in the JSON is important. Similarly, it's important if the common user interface is raw JSON editing. Including `None` in the JSON would seem less important if all of your editors were built on deserializing with information about what classes the JSON contains.

Am I making sense? 

> Would it be especially painful to create our own serializer? I don't think JSON is all that complicated.

I was looking into this yesterday. [It's not](https://github.com/json4s/json4s#serializing-non-supported-types), however, we're trying to _override_ the `Option[_]` serializer which is a bit different. I wasn't able to get a custom serializer to be used. One approach may be to write a fully custom `ScanChain` serializer or something.

**Comment by aroelke** [comment]
From a user perspective, if the JSON file doesn't contain the empty fields, then if I add another fault model I have to modify the binding mechanism in addition to modifying Chiffre's code, unless there's a way for the binding mechanism to automatically detect all of the fault models and figure out what their scan fields are.  The more places code has to be edited to make a change, even a small one (especially a small one), the more likely it is that errors occur.

I do see what you mean that the binding mechanism will need to know what a `ScanChain` and `ScanChainConfig` are, but I was referring to it not needing to know about individual fault injectors and being able to figure out what is and isn't present just from the JSON file.

Writing a fully custom serializer was what I was referring to there.  It seems to me that modifying json4s to change its behavior for a specific type would be more difficult than just writing writing our own.

**Comment by seldridge** [comment]
There may be some support I sneaked into #15 related to binding that helps here. An abstract `ScanField` has a `bind(in: BigInt)` method. Other bind methods can be added, or you can override the existing one. One example of this is with the `ProbabilityBind` trait that defines `bind(probability: Double)` for getting a probability into a `BigInt`.

> The more places code has to be edited to make a change, even a small one (especially a small one), the more likely it is that errors occur.

You're absolutely right. There's a related problem of a user defining a new fault injector in a library and us needing to handle that. This type of problem came up with FIRRTL and I have a workaround that will likely work here (Java's `ServiceLoader`). But, yes, I think the correct approach would be to move all logic, including command line arguments, the internals of `ScanChainConfig`'s `bind` method, etc. inside each fault injector. Or, put differently, `ScanChainConfig` should be refactored to only work with concrete `ScanField` classes.

**Comment by aroelke** [comment]
So does that mean that the binding mechanism will be able to automatically detect all of the injectors that have been defined?  Ideally the only thing that a user should need to do to create a new injector is create subclasses of `Injector` and `InjectorInfo` (if applicable; I forget if `InjectorInfo` still exists), and then either the scan chain description file includes all of the new injector's fields or black magic happens and the binding agent can figure out the information it needs to know without having to be modified.

Incidentally, this was an issue I had with OldSpot and trying to add new aging models, but I don't think C++ has ways of doing this.  Right now it just uses a static instance of each model, which works okay but is kind of ugly.  When I release the code, I might go back and try to make it better.

**Comment by aroelke** [comment]
This latest set of changes just updates this PR to reflect the latest changes to master.  I removed the ScanChainConfig tests because they don't make sense anymore, but left the file there because tests will need to be present in the future.

While I restored the other tests to working status, I didn't restore default values to `ScanField`s because I don't think we've arrived at a solution for how to interface them with `ScanChainConfig.scala` yet.

**Comment by seldridge** [comment]
I'm digging into this. One thing I found is that Json4s has an empty value strategy you can change. This will cause Option to serialize as "null". Something like:
```scala
  def serialize(s: ScanChain): String = {
    implicit val formats = Serialization
      .formats(FullTypeHints(getTags(s)))
      .preservingEmptyValues
      .withTypeHintFieldName("class")
    writePretty(s)
  }
```
Will serialize:
```scala
case class TestInfo(hello: Option[Int] = None) extends InjectorInfo {
  val fields = Seq.empty
}
```
To: 
```json
{
  "name":"Top.Top.d",
  "injector":{
    "class":"chiffreTests.scan.TestInfo",
    "hello":null
  }
}

```
Not documented, but it's in the json4s code... You can also define custom `EmptyValueStrategy`s.

Hold off on this, though. I'm looking into writing a custom serializer (or something in that direction). I like the existing approach for `InjectorInfo` and how binding works, but I think that the underlying `fields` need to be serialized individually.

**Comment by aroelke** [comment]
Is it possible to have `InjectorInfo` inherit from a trait or abstract class and implement some method that json4s can call to serialize and deserialize it, similar to how Java has the `Serializable`/`Externalizable` interfaces?  Or is the only way to get it to serialize a class is to make it a case class and include fields that need to be serialized in its parameters?

**Comment by seldridge** [comment]
Working on this... it's possible to do it the way you suggest, but it's annoying for the user. Every user has to write a json4s serializer. However, json4s already knows how to serialize arbitrary case classes. We just have to add a hook of sorts that causes it to do _more_ than just serialize the case class. Namely, to also serialize the scan fields. When it deserializes, we need to do construction from the case class and then bind the scan fields.

I have serialization working. Trying to finish up the deserializer. Final output may change, but here's what the serialized output looks like now:
```json
{
  "id-0":[
    {
      "name":"Top.Top.a",
      "injector":{
        "class":"chiffre.inject.StuckAtInjectorInfo",
        "bitWidth":5,
        "fields":[
          {
            "class":"chiffre.inject.Mask",
            "width":5,
            "value":null
          },
          {
            "class":"chiffre.inject.StuckAt",
            "width":5,
            "value":null
          }
        ]
      }
    }
  ]
}
```

Does that seem like a reasonable API for editing the JSON?

**Comment by aroelke** [comment]
Yes, that seems reasonable.  It's essentially what I was envisioning when I started this PR, but wasn't able to do due to limitations of json4s and/or my lack of knowledge of it.  I still think this is possible using json4s and a custom serialization method like I mentioned earlier, without needing users to define their own serialization, but if you already have a serializer done then it's better to just go with that.

**Comment by seldridge** [comment]
Thanks for updating this to match the new binds and JSON. I was taking a look at this with a slightly higher level test that I thought would pass, but it isn't. Basically, I'm doing double injection into a module with the same fault injector and using different widths, but doing a full test with a Chisel driver. I'm looking into it...
```diff
diff --git a/src/test/scala/chiffreTests/passes/FaultInstrumentationTransformSpec.scala b/src/test/scala/chiffreTests/passes/FaultInstrumentationTransformSpec.scala
index 854ef62..900ea61 100644
--- a/src/test/scala/chiffreTests/passes/FaultInstrumentationTransformSpec.scala
+++ b/src/test/scala/chiffreTests/passes/FaultInstrumentationTransformSpec.scala
@@ -44,14 +44,18 @@ class TestController(val scanId: String) extends Module with ChiffreController {
 
 class TestInjectee(faulty: Boolean) extends Module with ChiffreInjectee {
   val io = IO(new Bundle{})
-  val x = RegInit(0.U(1.W))
+  val x = RegInit(~0.U(1.W))
+  val y = RegInit(~0.U(2.W))
   val scanId = "id"
 
   if (faulty) {
     isFaulty(x, scanId, classOf[TestInjector])
     assert(x === RegNext(~x), "Faulty register 'x' did not flip")
+    assert(y === RegNext(y), "Faulty register 'y' did not flip")
   } else {
+    isFaulty(y, scanId, classOf[TestInjector])
     assert(x === RegNext(x), "Non-faulty register 'x' did not hold its value")
+    assert(y === RegNext(~y), "Non-faulty register 'y' did not hold its value")
   }
 }
```

**Comment by aroelke** [comment]
That's odd.  I get a FIRRTL error when I run that test, but when I do the same thing with Rocket Chip and annotate both reg_frm and reg_fflags (which are UInts with different widths) with a stuck-at injector, it compiles fine.

**Comment by seldridge** [comment]
Looking at this, I think I defined TestInjector as being 1-bit. If it's working on rocket-chip, then it should work here. I'm traveling, but I should be able to give this a review today.

**Comment by aroelke** [comment]
I corrected the width of `TestInjector` and played around with the placement of `isFaulty(x,...)` and `isFaulty(y,...)` and I think it has to do with your `faulty` switch.  I think what's happening is that the transform is creating two injector modules with the same name, since each version of the tester module has only one faulty element, one of which gets erased further down in other FIRRTL transforms.  The result is that the same injector module is used for both faulty elements, which happens to be the one that's one bit wide.  For example, it works if I put both `isFaulty` calls in the same block of the if statement.

**Comment by seldridge** [comment]
Digging into this. Two issues: 
1. this PR needs to use the circuit name instead of the instance name when instantiating the instance
2. the circuit name needs to match the top level name

Fixing 2 has me looking at the inline compile method. In the situation where this renames a module due to a circuit namespace conflict, it isn't renaming the circuit. 

You wind up with something like: 
```firrtl
circuit TestInjector :
  module TestInjector_0 :
    input clock : Clock
    input reset : UInt<1>
    output io : { scan : { flip clk : UInt<1>, flip en : UInt<1>, flip in : UInt<1>, out : UInt<1>}, flip in : UInt<2>, out : UInt<2>}
```

This actually violates my understanding of the FIRRTL spec... 

Anyway, there's a further problem of submodules in a subcircuit getting renamed means that the `DefInstance`s need to get renamed, too. That's not happening here, but it clearly could.

**Comment by aroelke** [comment]
I missed your comment with that latest commit, but it addresses 2.

For 1, I think what's happening is that `defi` is being defined by the top-level subcircuit name and not the actual module name, which is why 2 is necessary.  When I first made this PR, I didn't know how to fix that and ended up just making sure that the module and instance names matched (i.e. used `defi` for both).  The most proper method would be to extract the injector module from the subcircuit and create a `WDefInstance` of that, then use that `WDefInstance`'s name to make connections.

Either way, we'll need to use something like the admittedly somewhat awkward naming scheme I added to ensure that two versions of the same injector module with different parameters are actually unique modules.

**Comment by seldridge** [comment]
Yeah, `genName` was already doing the right thing as far as I was concerned. It's just that issue of not renaming the circuit properly. Usually manual name mangling that doesn't use a namespace is going to fail for some case.

Generally, there should be something in FIRRTL that will merge two circuits. It doesn't exist as far as I'm aware, but is likely a PR on FIRRTL proper. It shouldn't be too hard. Just rename all modules into the other namespace, then locally rename definstances. We can prototype something here that does that (assuming this is the route that makes sense).

**Pull request merged**
